# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev/nvidia-cpu-cards

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    sudo apt-get remove docker docker-engine docker.io containerd runc
    sudo apt-get update
    sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io

  displayName: 'Install docker'

- script: sudo apt install golang
  displayName: 'Install golang'

- script: make container
  displayName: 'Run a one-line script'
  env:
    ARCH: $(ARCH)
    IMAGE: $(IMAGE)
    TAG: $(TAG)
- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub'
    repository: '$(IMAGE)'
    command: 'push'
    tags: '$(TAG)'
