name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: release/v2.4.2

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: release/v2.4.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        run:  make build
        # env:
        #   GOARCH: amd64
        #   GOOS: linux

      - name: Get commit ID
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:v2.18.2_auth, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:$(date +%s)
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kube-state-metrics:v2.4.2, ${{ secrets.DOCKER_HUB_USERNAME }}/kube-state-metrics:${{ steps.vars.outputs.sha_short }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
